include macro.h
.8086
.model huge
.stack 1024
.data
	welcome	db	"Press any key to start$"
	hint	db	"Press e to leave game$"
	data1	dw	18
	data2	dw	18
	x	dw	329
	y	dw	80
	model	db	0
	randonum	db	0
	blockcolor	db	03h
	numberofclear	db	0
	level		db	10
	speed		dw	6000h
.code
.startup
	SetMode 12h
	SetColor 00h
	Tblock2		80,100,02h
	Iblock1		80,160,0Bh
	Lvblock2	160,100,0Ch
	Tblock1		140,160,02h
	Lblock		160,200,01h
	Tblock2		240,100,02h
	Iblock1		240,160,0Bh
	Lvblock2	320,100,0Ch
	Lvblock		320,120,0Ch
	Iblock1		300,180,0Bh
	zblock1		340,180,0Ah
	zvblock		380,220,04h	
	Iblock1		440,120,0Bh
	Iblock1		440,200,0Bh	
	Lblock2		540,100,01h
	Iblock1		500,120,0Bh
	tenblock	520,160,0Eh
	Iblock1		560,200,0Bh
	Lblock		520,220,01h
	SetCursor	20,30
	PrintStr	welcome
	GetChar
	SetMode 12h
	SetColor 00h
	SetCursor	0,0
	PrintStr	hint
	call	background	
beginning:
	call	clearrow
	call	levelup
	mov	x,329
	mov	y,80
	color_get_mid	x,y,blockcolor
	cmp	blockcolor,03h
	jne	leave
	mov	model,0
	mov	blockcolor,03h
	xor	ax,ax
	random_number randonum
drop:
	cmp	model,0
	je	block_pr
	cmp	model,1
	je	block_pr1
	cmp	model,2
	je	block_pr2
	cmp	model,3
	je	block_pr3
block_pr:
	cmp	randonum,0
	je	Lblock_pr
	cmp	randonum,1
	je	Lvblock_pr
	cmp	randonum,2
	je	Tblock_pr
	cmp	randonum,3
	je	zblock_pr
	cmp	randonum,4
	je	zvblock_pr
	cmp	randonum,5
	je	Iblock_pr
	cmp	randonum,6
	je	tenblock_pr
block_pr1:
	cmp	randonum,0
	je	Lblock_pr1
	cmp	randonum,1
	je	Lvblock_pr1
	cmp	randonum,2
	je	Tblock_pr1
	cmp	randonum,3
	je	zblock_pr1
	cmp	randonum,4
	je	zvblock_pr1
	cmp	randonum,5
	je	Iblock_pr1
block_pr2:
	cmp	randonum,0
	je	Lblock_pr2
	cmp	randonum,1
	je	Lvblock_pr2
	cmp	randonum,2
	je	Tblock_pr2
block_pr3:
	cmp	randonum,0
	je	Lblock_pr3
	cmp	randonum,1
	je	Lvblock_pr3
	cmp	randonum,2
	je	Tblock_pr3
Tblock_pr:
	Tblock	x,y,02h
	jmp	Delay_in
Tblock_pr1:
	Tblock1	x,y,02h
	jmp	Delay_in
Tblock_pr2:
	Tblock2	x,y,02h
	jmp	Delay_in
Tblock_pr3:
	Tblock3	x,y,02h
	jmp	Delay_in
Lblock_pr:
	Lblock	x,y,01h
	jmp	Delay_in
Lblock_pr1:
	Lblock1	x,y,01h
	jmp	Delay_in
Lblock_pr2:
	Lblock2	x,y,01h
	jmp	Delay_in
Lblock_pr3:
	Lblock3	x,y,01h
	jmp	Delay_in
Lvblock_pr:
	Lvblock	x,y,0ch
	jmp	Delay_in
Lvblock_pr1:
	Lvblock1 x,y,0ch
	jmp	Delay_in
Lvblock_pr2:
	Lvblock2 x,y,0ch
	jmp	Delay_in
Lvblock_pr3:
	Lvblock3 x,y,0ch
	jmp	Delay_in
zblock_pr:
	zblock	x,y,0Ah
	jmp	Delay_in
zblock_pr1:
	zblock1	x,y,0Ah
	jmp	Delay_in
zvblock_pr:
	zvblock	x,y,04h
	jmp	Delay_in
zvblock_pr1:
	zvblock1 x,y,04h
	jmp	Delay_in
Iblock_pr:
	Iblock	x,y,0Bh
	jmp	Delay_in
Iblock_pr1:
	Iblock1	x,y,0Bh
	jmp	Delay_in
tenblock_pr:
	tenblock x,y,0Eh
Delay_in:
	call	Input
	call	delay
	call	Input
	call	delay
	call	Input
	call	delay
	cmp	model,0
	je	mid
	cmp	model,1
	je	mid1
	cmp	model,2
	je	mid2
	cmp	model,3
	je	mid3
mid:
	cmp	randonum,0
	je	Lmid
	cmp	randonum,1
	je	Lvmid
	cmp	randonum,2
	je	Tmid
	cmp	randonum,3
	je	zmid
	cmp	randonum,4
	je	zvmid
	cmp	randonum,5
	je	Imid
	cmp	randonum,6
	je	tenmid
mid1:
	cmp	randonum,0
	je	Lmid1
	cmp	randonum,1
	je	Lvmid1
	cmp	randonum,2
	je	Tmid1
	cmp	randonum,3
	je	zmid1
	cmp	randonum,4
	je	zvmid1
	cmp	randonum,5
	je	Imid1
mid2:
	cmp	randonum,0
	je	Lmid2
	cmp	randonum,1
	je	Lvmid2
	cmp	randonum,2
	je	Tmid2
mid3:
	cmp	randonum,0
	je	Lmid3
	cmp	randonum,1
	je	Lvmid3
	cmp	randonum,2
	je	Tmid3
Tmid:
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	add	x,40
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning	
	sub	x,20
	Tblock	x,y,03h
	add	y,20
	jmp	drop
Tleft:
	push	cx
	push	x
	push	y
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	x,20
	add	y,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Tblock	x,y,03h
	sub	x,20
	Tblock	x,y,02h
	pop	cx
	jmp	D2
Tright:
	push	cx
	push	x
	push	y
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	x,20
	add	y,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Tblock	x,y,03h
	add	x,20
	Tblock	x,y,02h
	pop	cx
	jmp	D2
Tmid1:
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	y,20
	add	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	x,20
	add	y,20
	Tblock1	x,y,03h
	add	y,20
	jmp	drop
Tleft1:
	push	cx
	push	x
	push	y
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	y,40
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Tblock1	x,y,03h
	sub	x,20
	Tblock1	x,y,02h
	pop	cx
	jmp	D2
Tright1:
	push	cx
	push	x
	push	y
	add	x,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	x,20
	add	y,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	y,40
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Tblock1	x,y,03h
	add	x,20
	Tblock1	x,y,02h
	pop	cx
	jmp	D2
Tmid2:
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	y,20
	sub	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	add	x,40
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	x,20
	add	y,20
	Tblock2	x,y,03h
	add	y,20
	jmp	drop	
Tleft2:
	push	cx
	push	x
	push	y
	sub	x,20
	color_get_left x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	x,20
	add	y,20
	color_get_left x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Tblock2	x,y,03h
	sub	x,20
	Tblock2	x,y,02h
	pop	cx
	jmp	D2
Tright2:
	push	cx
	push	x
	push	y
	add	x,20
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	x,20
	add	y,20
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Tblock2	x,y,03h
	add	x,20
	Tblock2	x,y,02h
	pop	cx
	jmp	D2
Tmid3:
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	y,20
	sub	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	add	x,20
	add	y,20
	Tblock3	x,y,03h
	add	y,20
	jmp	drop
Tleft3:
	push	cx
	push	x
	push	y
	sub	x,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	x,20
	add	y,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	y,40
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Tblock3	x,y,03h
	sub	x,20
	Tblock3	x,y,02h
	pop	cx
	jmp	D2
Tright3:
	push	cx
	push	x
	push	y
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,20
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	y,20
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Tblock3	x,y,03h
	add	x,20
	Tblock3	x,y,02h
	pop	cx
	jmp	D2	
Tr1:
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border
	Tblock	x,y,03h
	Tblock1	x,y,02h
	jmp	D2
Tr2:	
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border
	Tblock1 x,y,03h
	Tblock2	x,y,02h
	jmp	D2
Tr3:
	color_get_up	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border
	Tblock2 x,y,03h
	Tblock3 x,y,02h
	jmp	D2
Tr4:
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border
	Tblock3	x,y,03h
	Tblock	x,y,02h
	jmp	D2
Lmid:
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	add	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	x,40
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	add	x,20
	Lblock	x,y,03h
	add	y,20
	jmp	drop
Lleft:
	push	cx
	push	x
	push	y
	sub	x,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Lblock	x,y,03h
	sub	x,20
	Lblock	x,y,01h
	pop	cx
	jmp	D2
Lright:
	push	cx
	push	x
	push	y
	color_get_mid x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,20
	add	x,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Lblock	x,y,03h
	add	x,20
	Lblock	x,y,01h
	pop	cx
	jmp	D2
Lmid1:
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	add	x,20
	sub	y,40
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	x,20
	add	y,40
	Lblock1	x,y,03h
	add	y,20
	jmp	drop
Lleft1:
	push	cx
	push	x
	push	y
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	y,40
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Lblock1	x,y,03h
	sub	x,20
	Lblock1	x,y,01h
	pop	cx
	jmp	D2
Lright1:
	push	cx
	push	x
	push	y
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	y,40
	add	x,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Lblock1	x,y,03h
	add	x,20
	Lblock1	x,y,01h
	pop	cx
	jmp	D2
Lmid2:
	add	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	x,20
	sub	y,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	add	x,20
	add	y,20
	Lblock2	x,y,03h
	add	y,20
	jmp	drop
Lleft2:
	push	cx
	push	x
	push	y
	sub	x,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	x,40
	add	y,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Lblock2	x,y,03h
	sub	x,20
	Lblock2	x,y,01h
	pop	cx
	jmp	D2
Lright2:
	push	cx
	push	x
	push	y
	add	x,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Lblock2	x,y,03h
	add	x,20
	Lblock2	x,y,01h
	pop	cx
	jmp	D2
Lmid3:
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	add	x,20
	Lblock3	x,y,03h
	add	y,20
	jmp	drop
Lleft3:
	push	cx
	push	x
	push	y
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	y,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,40
	sub	x,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Lblock3	x,y,03h
	sub	x,20
	Lblock3	x,y,01h
	pop	cx
	jmp	D2
Lright3:
	push	cx
	push	x
	push	y
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	y,40
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Lblock3	x,y,03h
	add	x,20
	Lblock3	x,y,01h
	pop	cx
	jmp	D2
Lr1:
	push	x
	push	y
	color_get_mid	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	color_get_up	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	sub	y,20
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	pop	y
	pop	x
	Lblock	x,y,03h
	Lblock1	x,y,01h
	jmp	D2
Lr2:	
	push	x
	push	y
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	add	y,20
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	pop	y
	pop	x
	Lblock1 x,y,03h
	Lblock2	x,y,01h
	jmp	D2
Lr3:
	push	x
	push	y
	color_get_up	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	add	y,20
	color_get_mid	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	pop	y
	pop	x
	Lblock2 x,y,03h
	Lblock3 x,y,01h
	jmp	D2
Lr4:
	push	x
	push	y
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	add	y,20
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	pop	y
	pop	x
	Lblock3	x,y,03h
	Lblock	x,y,01h
	jmp	D2
Lvmid:
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	add	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	x,40
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	add	x,20
	Lvblock	x,y,03h
	add	y,20
	jmp	drop
Lvleft:
	push	cx
	push	x
	push	y
	add	x,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	x,40
	add	y,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Lvblock	x,y,03h
	sub	x,20
	Lvblock	x,y,0ch
	pop	cx
	jmp	D2
Lvright:
	push	cx
	push	x
	push	y
	add	x,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Lvblock	x,y,03h
	add	x,20
	Lvblock	x,y,0ch
	pop	cx
	jmp	D2
Lvmid1:
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	add	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	x,20
	Lvblock1 x,y,03h
	add	y,20
	jmp	drop
Lvleft1:
	push	cx
	push	x
	push	y
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	y,40
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Lvblock1 x,y,03h
	sub	x,20
	Lvblock1 x,y,0ch
	pop	cx
	jmp	D2
Lvright1:
	push	cx
	push	x
	push	y
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	y,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,40
	add	x,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Lvblock1 x,y,03h
	add	x,20
	Lvblock1 x,y,0ch
	pop	cx
	jmp	D2
Lvmid2:
	sub	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	y,20
	add	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	add	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	x,20
	add	y,20
	Lvblock2 x,y,03h
	add	y,20
	jmp	drop
Lvleft2:
	push	cx
	push	x
	push	y
	sub	x,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Lvblock2 x,y,03h
	sub	x,20
	Lvblock2 x,y,0ch
	pop	cx
	jmp	D2
Lvright2:
	push	cx
	push	x
	push	y
	add	x,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	x,40
	add	y,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Lvblock2 x,y,03h
	add	x,20
	Lvblock2 x,y,0ch
	pop	cx
	jmp	D2
Lvmid3:
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	y,40
	sub	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	add	y,40
	add	x,20
	Lvblock3 x,y,03h
	add	y,20
	jmp	drop
Lvleft3:
	push	cx
	push	x
	push	y
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	y,40
	sub	x,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Lvblock3 x,y,03h
	sub	x,20
	Lvblock3 x,y,0ch
	pop	cx
	jmp	D2
Lvright3:
	push	cx
	push	x
	push	y
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	y,40
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Lvblock3 x,y,03h
	add	x,20
	Lvblock3 x,y,0ch
	pop	cx
	jmp	D2
Lvr1:
	color_get_mid	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border
	color_get_up	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border	
	Lvblock	x,y,03h
	Lvblock1 x,y,0ch
	jmp	D2
Lvr2:	
	push	x
	push	y
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	add	y,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	pop	y
	pop	x
	Lvblock1 x,y,03h
	Lvblock2 x,y,0ch
	jmp	D2
Lvr3:
	push	x
	push	y
	color_get_up	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	sub	y,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	pop	y
	pop	x
	Lvblock2 x,y,03h
	Lvblock3 x,y,0ch
	jmp	D2
Lvr4:
	push	x
	push	y
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	add	y,20
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	pop	y
	pop	x
	Lvblock3 x,y,03h
	Lvblock	x,y,0ch
	jmp	D2
r1:
	cmp	randonum,0
	je	Lr1
	cmp	randonum,1
	je	Lvr1
	cmp	randonum,2
	je	Tr1
	cmp	randonum,3
	je	zr1
	cmp	randonum,4
	je	zvr1
	cmp	randonum,5
	je	Ir1
r2:
	cmp	randonum,0
	je	Lr2
	cmp	randonum,1
	je	Lvr2
	cmp	randonum,2
	je	Tr2
	cmp	randonum,3
	je	zr2
	cmp	randonum,4
	je	zvr2
	cmp	randonum,5
	je	Ir2
r3:
	cmp	randonum,0
	je	Lr3
	cmp	randonum,1
	je	Lvr3
	cmp	randonum,2
	je	Tr3
r4:
	cmp	randonum,0
	je	Lr4
	cmp	randonum,1
	je	Lvr4
	cmp	randonum,2
	je	Tr4
border:
	cmp	model,0
	je	modellimit
	dec	model
	xor	ax,ax
	jmp	D2
border1:
	pop	y
	pop	x
	cmp	model,0
	je	modellimit
	dec	model
	xor	ax,ax
	jmp	D2
modellimit:
	cmp	randonum,2
	ja	zmodellimit
	mov	model,3
	xor	ax,ax
	jmp	D2
zmodellimit:
	mov	model,1
	xor	ax,ax
	jmp	D2
move_fail:
	pop	y
	pop	x
	pop	cx
	xor	ax,ax
	jmp	D2
left:
	cmp	randonum,0
	je	Lleft
	cmp	randonum,1
	je	Lvleft
	cmp	randonum,2
	je	Tleft
	cmp	randonum,3
	je	zleft
	cmp	randonum,4
	je	zvleft
	cmp	randonum,5
	je	Ileft
	cmp	randonum,6
	je	tenleft
left1:
	cmp	randonum,0
	je	Lleft1
	cmp	randonum,1
	je	Lvleft1
	cmp	randonum,2
	je	Tleft1
	cmp	randonum,3
	je	zleft1
	cmp	randonum,4
	je	zvleft1
	cmp	randonum,5
	je	Ileft1
left2:
	cmp	randonum,0
	je	Lleft2
	cmp	randonum,1
	je	Lvleft2
	cmp	randonum,2
	je	Tleft2
left3:
	cmp	randonum,0
	je	Lleft3
	cmp	randonum,1
	je	Lvleft3
	cmp	randonum,2
	je	Tleft3
right:
	cmp	randonum,0
	je	Lright
	cmp	randonum,1
	je	Lvright
	cmp	randonum,2
	je	Tright
	cmp	randonum,3
	je	zright
	cmp	randonum,4
	je	zvright
	cmp	randonum,5
	je	Iright
	cmp	randonum,6
	je	tenright
right1:
	cmp	randonum,0
	je	Lright1
	cmp	randonum,1
	je	Lvright1
	cmp	randonum,2
	je	Tright1
	cmp	randonum,3
	je	zright1
	cmp	randonum,4
	je	zvright1
	cmp	randonum,5
	je	Iright1
right2:
	cmp	randonum,0
	je	Lright2
	cmp	randonum,1
	je	Lvright2
	cmp	randonum,2
	je	Tright2
right3:
	cmp	randonum,0
	je	Lright3
	cmp	randonum,1
	je	Lvright3
	cmp	randonum,2
	je	Tright3
rotation:
	cmp	y,80
	je	D2
	cmp	randonum,2
	ja	rotation1
	inc	model
	cmp	model,1
	je	r1
	cmp	model,2
	je	r2
	cmp	model,3
	je	r3
	mov	model,0
	jmp	r4
rotation1:
	inc	model
	cmp	model,1
	je	r1
	mov	model,0
	jmp	r2
leftt:
	cmp	model,0
	je	left
	cmp	model,1
	je	left1
	cmp	model,2
	je	left2
	cmp	model,3
	je	left3
rightt:
	cmp	model,0
	je	right
	cmp	model,1
	je	right1
	cmp	model,2
	je	right2
	cmp	model,3
	je	right3
fall:
	cmp	randonum,0
	je	Lfall_mod
	cmp	randonum,1
	je	Lvfall_mod
	cmp	randonum,2
	je	Tfall_mod
	cmp	randonum,3
	je	zfall_mod
	cmp	randonum,4
	je	zvfall_mod
	cmp	randonum,5
	je	Ifall_mod
	cmp	randonum,6
	je	tenfall
tenfall:
	tenblock x,y,03h
	push	x
	push	y
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	tentouch
	add	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	tentouch
	pop	y
	pop	x
	add	y,20
	jmp	tenfall
tentouch:
	pop	y
	pop	x
	tenblock x,y,0Eh
	jmp	beginning
Ifall_mod:
	cmp	model,0
	je	Ifall
	cmp	model,1
	je	Ifall1
Ifall:
	Iblock	x,y,03h
	push	x
	push	y
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Itouch
	sub	x,40
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Itouch
	add	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Itouch
	add	x,40
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Itouch
	pop	y
	pop	x
	add	y,20
	jmp	Ifall
Ifall1:
	Iblock1	x,y,03h
	add	y,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Itouch1
	jmp	Ifall1
Itouch:
	pop	y
	pop	x
	Iblock	x,y,0Bh
	jmp	beginning
Itouch1:
	sub	y,20
	Iblock1	x,y,0Bh
	jmp	beginning
zvfall_mod:
	cmp	model,0
	je	zvfall
	cmp	model,1
	je	zvfall1
zvfall:	
	zvblock	x,y,03h
	push	x
	push	y
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	zvtouch
	add	y,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	zvtouch
	add	y,20
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	zvtouch
	pop	y
	pop	x
	add	y,20
	jmp	zvfall
zvfall1:
	zvblock1 x,y,03h
	push	x
	push	y
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	zvtouch1
	add	y,20
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	zvtouch1
	pop	y
	pop	x
	add	y,20
	jmp	zvfall1
zvtouch:
	pop	y
	pop	x
	zvblock	x,y,04h
	jmp	beginning
zvtouch1:
	pop	y
	pop	x
	zvblock1 x,y,04h
	jmp	beginning
zfall_mod:
	cmp	model,0
	je	zfall
	cmp	model,1
	je	zfall1
zfall:
	zblock	x,y,03h
	push	x
	push	y
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	ztouch
	sub	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	ztouch
	add	x,20
	add	y,20
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	ztouch
	pop	y
	pop	x
	add	y,20
	jmp	zfall
zfall1:
	zblock1	x,y,03h
	push	x
	push	y
	add	y,20
	color_get_mid	x,y,blockcolor
	cmp	blockcolor,03h
	jne	ztouch1
	add	y,20
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	ztouch1
	pop	y
	pop	x
	add	y,20
	jmp	zfall1
ztouch:
	pop	y
	pop	x
	zblock	x,y,0Ah
	jmp	beginning
ztouch1:
	pop	y
	pop	x
	zblock1	x,y,0Ah
	jmp	beginning
Lfall_mod:
	cmp	model,0
	je	Lfall
	cmp	model,1
	je	Lfall1
	cmp	model,2
	je	Lfall2
	cmp	model,3
	je	Lfall3
Lfall:
	Lblock	x,y,03h
	push	x
	push	y
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Ltouch
	sub	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Ltouch
	add	x,40
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Ltouch
	pop	y
	pop	x
	add	y,20
	jmp	Lfall
Lfall1:
	Lblock1	x,y,03h
	push	x
	push	y
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Ltouch1
	add	x,20
	sub	y,40
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Ltouch1
	pop	y
	pop	x
	add	y,20
	jmp	Lfall1
Lfall2:
	Lblock2	x,y,03h
	push	x
	push	y
	sub	y,20
	sub	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Ltouch2
	add	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Ltouch2
	add	x,20
	add	y,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Ltouch2
	pop	y
	pop	x
	add	y,20
	jmp	Lfall2
Lfall3:
	Lblock3	x,y,03h
	push	x
	push	y
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Ltouch3
	sub	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Ltouch3
	pop	y
	pop	x
	add	y,20
	jmp	Lfall3
Ltouch:
	pop	y
	pop	x
	Lblock	x,y,01h
	jmp	beginning
Ltouch1:
	pop	y
	pop	x
	Lblock1	x,y,01h
	jmp	beginning
Ltouch2:
	pop	y
	pop	x
	Lblock2	x,y,01h
	jmp	beginning
Ltouch3:
	pop	y
	pop	x
	Lblock3	x,y,01h
	jmp	beginning
Lvfall_mod:
	cmp	model,0
	je	Lvfall
	cmp	model,1
	je	Lvfall1
	cmp	model,2
	je	Lvfall2
	cmp	model,3
	je	Lvfall3
Lvfall:
	Lvblock	x,y,03h
	push	x
	push	y
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Lvtouch
	sub	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Lvtouch
	add	x,40
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Lvtouch
	pop	y
	pop	x
	add	y,20
	jmp	Lvfall
Lvfall1:
	Lvblock1 x,y,03h
	push	x
	push	y
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Lvtouch1
	add	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Lvtouch1
	pop	y
	pop	x
	add	y,20
	jmp	Lvfall1
Lvfall2:
	Lvblock2 x,y,03h
	push	x
	push	y
	sub	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Lvtouch2
	add	x,20
	sub	y,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Lvtouch2
	add	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Lvtouch2
	pop	y
	pop	x
	add	y,20
	jmp	Lvfall2
Lvfall3:
	Lvblock3 x,y,03h
	push	x
	push	y
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Lvtouch3
	sub	x,20
	sub	y,40
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Lvtouch3
	pop	y
	pop	x
	add	y,20
	jmp	Lvfall3
Lvtouch:
	pop	y
	pop	x
	Lvblock	x,y,0ch
	jmp	beginning
Lvtouch1:
	pop	y
	pop	x
	Lvblock1 x,y,0ch
	jmp	beginning
Lvtouch2:
	pop	y
	pop	x
	Lvblock2 x,y,0ch
	jmp	beginning
Lvtouch3:
	pop	y
	pop	x
	Lvblock3 x,y,0ch
	jmp	beginning
Tfall_mod:
	cmp	model,0
	je	Tfall
	cmp	model,1
	je	Tfall1
	cmp	model,2
	je	Tfall2
	cmp	model,3
	je	Tfall3
Tfall:
	Tblock	x,y,03h
	push	x
	push	y
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Ttouch
	add	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Ttouch
	sub	x,40
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Ttouch
	pop	y
	pop	x
	add	y,20
	jmp	Tfall
Tfall1:
	Tblock1	x,y,03h
	push	x
	push	y
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Ttouch1
	add	x,20
	sub	y,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Ttouch1
	pop	y
	pop	x
	add	y,20
	jmp	Tfall1
Tfall2:
	Tblock2	x,y,03h
	push	x
	push	y
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Ttouch2
	add	x,20
	sub	y,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Ttouch2
	sub	x,40
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Ttouch2
	pop	y
	pop	x
	add	y,20
	jmp	Tfall2
Tfall3:
	Tblock3	x,y,03h
	push	x
	push	y
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Ttouch3
	sub	x,20
	sub	y,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	Ttouch3
	pop	y
	pop	x
	add	y,20
	jmp	Tfall3
Ttouch:
	pop	y
	pop	x
	Tblock	x,y,02h
	jmp	beginning
Ttouch1:
	pop	y
	pop	x
	Tblock1	x,y,02h
	jmp	beginning
Ttouch2:
	pop	y
	pop	x
	Tblock2	x,y,02h
	jmp	beginning
Ttouch3:
	pop	y
	pop	x
	Tblock3	x,y,02h
	jmp	beginning
zmid:
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	add	x,40
	sub	y,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning	
	sub	x,20
	add	y,20
	zblock	x,y,03h
	add	y,20
	jmp	drop
zleft:
	push	cx
	push	x
	push	y
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	x,20
	add	y,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	zblock	x,y,03h
	sub	x,20
	zblock	x,y,0Ah
	pop	cx
	jmp	D2
zright:
	push	cx
	push	x
	push	y
	add	x,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	x,20
	add	y,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	zblock	x,y,03h
	add	x,20
	zblock	x,y,0Ah
	pop	cx
	jmp	D2
zmid1:
	add	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	add	y,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	x,20
	sub	y,20	
	zblock1	x,y,03h
	add	y,20
	jmp	drop
zleft1:
	push	cx
	push	x
	push	y
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	y,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,40
	color_get_mid	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	zblock1	x,y,03h
	sub	x,20
	zblock1	x,y,0Ah
	pop	cx
	jmp	D2
zright1:
	push	cx
	push	x
	push	y
	add	x,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	y,40
	color_get_mid	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	zblock1	x,y,03h
	add	x,20
	zblock1	x,y,0Ah
	pop	cx
	jmp	D2
zr1:
	push	x
	push	y
	color_get_up	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	add	y,20
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	pop	y
	pop	x
	zblock	x,y,03h
	zblock1	x,y,0Ah
	jmp	D2
zr2:
	push	x
	push	y
	add	y,20
	color_get_mid	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	pop	y
	pop	x
	zblock1	x,y,03h
	zblock	x,y,0Ah
	jmp	D2
zvmid:
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	add	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	x,40
	add	y,20
	color_get_mid	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning	
	add	x,20
	sub	y,20
	zvblock	x,y,03h
	add	y,20
	jmp	drop
zvleft:
	push	cx
	push	x
	push	y
	sub	x,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,20
	color_get_mid	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	zvblock	x,y,03h
	sub	x,20
	zvblock	x,y,04h
	pop	cx
	jmp	D2
zvright:
	push	cx
	push	x
	push	y
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	x,20
	add	y,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	zvblock	x,y,03h
	add	x,20
	zvblock	x,y,04h
	pop	cx
	jmp	D2
zvmid1:
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	add	y,20
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	y,20	
	zvblock1 x,y,03h
	add	y,20
	jmp	drop
zvleft1:
	push	cx
	push	x
	push	y
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	y,40
	color_get_mid	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	zvblock1 x,y,03h
	sub	x,20
	zvblock1 x,y,04h
	pop	cx
	jmp	D2
zvright1:
	push	cx
	push	x
	push	y
	add	x,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,20
	color_get_mid x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	y,40
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	zvblock1 x,y,03h
	add	x,20
	zvblock1 x,y,04h
	pop	cx
	jmp	D2
zvr1:
	push	x
	push	y
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	sub	y,20
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	pop	y
	pop	x
	zvblock	x,y,03h
	zvblock1 x,y,04h
	jmp	D2
zvr2:
	push	x
	push	y
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	add	y,20
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	pop	y
	pop	x
	zvblock1 x,y,03h
	zvblock x,y,04h
	jmp	D2
Imid:
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	x,40
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	add	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	add	x,40
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	x,20
	Iblock	x,y,03h
	add	y,20
	jmp	drop
Ileft:
	push	cx
	push	x
	push	y
	add	y,20
	sub	x,40
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Iblock	x,y,03h
	sub	x,20
	Iblock	x,y,0Bh
	pop	cx
	jmp	D2
Iright:
	push	cx
	push	x
	push	y
	add	x,20
	add	y,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Iblock	x,y,03h
	add	x,20
	Iblock	x,y,0Bh
	pop	cx
	jmp	D2
Imid1:
	add	y,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	y,20	
	Iblock1	x,y,03h
	add	y,20
	jmp	drop
Ileft1:
	push	cx
	push	x
	push	y
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	y,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,40
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Iblock1	x,y,03h
	sub	x,20
	Iblock1	x,y,0Bh
	pop	cx
	jmp	D2
Iright1:
	push	cx
	push	x
	push	y
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	sub	y,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,40
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,20
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	Iblock1	x,y,03h
	add	x,20
	Iblock1	x,y,0Bh
	pop	cx
	jmp	D2
Ir1:
	color_get_mid	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border
	color_get_up	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border
	Iblock	x,y,03h
	Iblock1	x,y,0Bh
	jmp	D2
Ir2:
	push	x
	push	y
	add	y,20
	color_get_right	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	sub	x,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	border1
	pop	y
	pop	x
	Iblock1	x,y,03h
	Iblock	x,y,0Bh
	jmp	D2
tenmid:
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	add	x,20
	color_get_down	x,y,blockcolor
	cmp	blockcolor,03h
	jne	beginning
	sub	x,20
	tenblock x,y,03h
	add	y,20
	jmp	drop
tenleft:
	push	cx
	push	x
	push	y
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,20
	color_get_left	x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	tenblock x,y,03h
	sub	x,20
	tenblock x,y,0Eh
	pop	cx
	jmp	D2
tenright:
	push	cx
	push	x
	push	y
	add	x,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	add	y,20
	color_get_right x,y,blockcolor
	cmp	blockcolor,03h
	jne	move_fail
	pop	y
	pop	x
	tenblock x,y,03h
	add	x,20
	tenblock x,y,0Eh
	pop	cx
	jmp	D2
leave:
.exit
background	proc	near
	mov	cx,229
	mov	dx,80
L4:
	push	cx
L5:	
	WrPixel	cx,dx,03h
	inc	cx
	cmp	cx,429
	jne	L5
	pop	cx
	inc	dx
	cmp	dx,480
	jne	L4
	ret
background	endp

delay	proc	near
	push	cx
	mov	cx,speed
	cmp	al,115
	je	quickdrop
	cmp	al,101
	je	leave
	cmp	al,32
	je	fall
	cmp	al,97
	je	leftt
	cmp	al,100
	je	rightt
	cmp	randonum,6
	je	D1
	cmp	al,119
	je	rotation
D1:
	mov	bp,3000h
D2:
	dec	bp
	cmp	bp,0
	jnz	D2
	loop	D1
quickdrop:
	pop	cx
	ret
delay	endp
Input	proc	near
	mov	ah,06h
	mov	dl,0ffh
	int	21h
	ret
Input	endp

clearrow	proc	near
	mov	x,229
	mov	y,460
CL0:
	color_get_mid	x,y,blockcolor
	cmp	blockcolor,03h
	je	CL1
	cmp	x,409
	je	CLneed
	add	x,20
	jmp	CL0
CL1:
	cmp	y,100
	je	CL_end
	sub	y,20
	mov	x,229	
	jmp	CL0
CLneed:
	inc	numberofclear
	mov	x,229
CLrep:
	block	x,y,03h
	cmp	x,409
	je	rowbias
	add	x,20
	jmp	CLrep
rowbias:
	mov	x,229
	push	y
bias:
	sub	y,20
	color_get_mid	x,y,blockcolor
	add	y,20
	block	x,y,blockcolor
	cmp	x,409
	je	rebias
	add	x,20
	jmp	bias
rebias:
	cmp	y,100
	je	reCL
	sub	y,20
	mov	x,229
	jmp	bias
reCL:
	pop	y
	mov	x,229
	jmp	CL0
CL_end:
	ret
clearrow	endp
levelup	proc	near
	cmp	speed,2500h
	jb	nspeedup
	mov	bl,level
	cmp	numberofclear,bl
	jb	nspeedup
	sub	numberofclear,bl
	add	level,10
	sub	speed,1500h
nspeedup:
	ret
levelup	endp
end